version: '3'
services:
  swarmpit:
    image: swarmpit/swarmpit:latest
    ports:
      - "888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
